<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\CulinaryBlog.Application\CulinaryBlog.Application.csproj" />
    <ProjectReference Include="..\..\CulinaryBlog.Infrastructure\CulinaryBlog.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" />
  </ItemGroup>

</Project>
